services:
  backend:
    build: "Backend API" # Directory containing the Dockerfile for your backend
    networks:
      - my-network
    depends_on:
      - database

  database:
    build: "database"
    env_file: ".env"
    environment:
      - DATABASE_URL=${DATABASE_URL} 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - my-network

  httpd:
    build: "Server HTTP"
    ports:
      - "80:80"  # Expose port 80 of the container to port 80 of the host machine
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network: