# Use the official Apache HTTPD image as the base
FROM httpd:latest

# Copy the index.html file to the Apache document root
COPY httpd.conf /usr/local/apache2/conf/httpd.conf

# Expose port 80 (default HTTP port)
EXPOSE 80
